target 'QYBaseProject' do
    pod 'ReactiveCocoa', '~> 2.4.7'
    pod 'JSONModel', '1.1.2'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'MBProgressHUD', '0.9.1'
    pod 'SDWebImage', '~>3.7'
    pod 'JSBadgeView'
    pod 'MJRefresh', '~> 3.0.7'
    pod 'AFDownloadRequestOperation', '~> 2.0.1'
    pod 'RATreeView', '1.0.3'
    #pod 'XYSideMenu', '~> 3.1'
    #pod 'ZipArchive', '~> 1.4.0'
    pod 'Reachability', '~> 3.2'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
    pod 'HMSegmentedControl', '~> 1.5.2'
    pod 'SECoreTextView', '~> 0.8.5'
    pod 'YYCache', '~> 1.0.3'
    pod 'BaiduMapKit', '~> 3.0.0'

end

target 'QYBaseProject_AppStore' do
    pod 'ReactiveCocoa', '~> 2.4.7'
    pod 'JSONModel', '1.1.2'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'MBProgressHUD', '0.9.1'
    pod 'SDWebImage', '~>3.7'
    pod 'JSBadgeView'
    pod 'MJRefresh', '~> 3.0.7'
    pod 'AFDownloadRequestOperation', '~> 2.0.1'
    pod 'RATreeView', '1.0.3'
    #pod 'XYSideMenu', '~> 3.1'
    #pod 'ZipArchive', '~> 1.4.0'
    pod 'Reachability', '~> 3.2'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
    pod 'HMSegmentedControl', '~> 1.5.2'
    pod 'SECoreTextView', '~> 0.8.5'
    pod 'YYCache', '~> 1.0.3'
    pod 'BaiduMapKit', '~> 3.0.0'

end

target 'QYNewAttendance' do
    pod 'ReactiveCocoa', '~> 2.4.7'
    pod 'JSONModel', '1.1.2'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'MBProgressHUD', '0.9.1'
    pod 'SDWebImage', '~>3.7'
    #    pod 'JSBadgeView'
    #    pod 'MJRefresh', '~> 3.0.7'
    pod 'AFDownloadRequestOperation', '~> 2.0.1'
    pod 'RATreeView', '1.0.3'
    #pod 'XYSideMenu', '~> 3.1'
    #pod 'ZipArchive', '~> 1.4.0'
    pod 'Reachability', '~> 3.2'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
    pod 'HMSegmentedControl', '~> 1.5.2'
    #    pod 'SECoreTextView', '~> 0.8.5'
    pod 'YYCache', '~> 1.0.3'
    pod 'BaiduMapKit', '~> 3.0.0'

end
